#!/usr/bin/env node
var debug = require('debug')('homemaker');
var app = require('../server');

app.set('port', process.env.PORT || 5005);

var server = app.listen(app.get('port'), function() {
  debug('listening on port ' + server.address().port);
});
